### ISSUE TITLE
Logré quebrar tu programa

### ISSUE THREAD

**Issue by Daviid-Perez-S** [jariasf/Online-Judges-Solutions#1]
Tiene errores, no es que sean sintácticos, sino **lógicos**.
Debes de crear premisas para la inserción de las vértices y sus respectivas aristas.
De insertarlas mal, el programa calcula mal las distancias, aún si se tratara de un grafo muy sencillo.

**Prueba con esto y mira como se quiebra:**

>>Vértices: 5
>> Aristas: 8

1 2 4
2 4 6
4 3 4
3 1 6
1 5 5
2 5 5
3 5 5
4 5 5

**-----------------------------------------------------------------**

_Resultado de tu programa:_

Ingrese el vertice inicial: 1
Distancias mas cortas iniciando en vertice 1
Vertice 1 , distancia mas corta = 0
Vertice 2 , distancia mas corta = 4
Vertice 3 , distancia mas corta = 14
Vertice 4 , distancia mas corta = 10
Vertice 5 , distancia mas corta = 5

**************Impresion de camino mas corto**************
Ingrese vertice destino: 3
1 2 4 3

**--------------------------------------------------------------**

La distancia al vértice 3 no es 14, sino 6. Es incorrecto. Sería bueno que cheques ese error.
Aún así es un muy buen esfuerzo de tu parte por hacer este programa. GRACIAS ^^

>> Te dejo la imagen del grafo con el que lo probé: 
![grafo prueba](https://user-images.githubusercontent.com/32287324/37883972-ddbdf9cc-306a-11e8-8eb9-3c66a1ece2c8.jpg)

**Comment by jariasf** [comment]
Buen punto! Un error al marcar el arreglo de visitados, ya esta arreglado. Gracias por reportar el error.

**Comment by Daviid-Perez-S** [comment]
Ohhh perfectooo. La verdad me ayudó mucho tu programa, y si ya está corregido ese problema, que mejor. Graciaaas.
Actualizaste el código con algún commit ya ??

**Comment by jariasf** [comment]
Si, ya esta actualizado el código. Solo era mover una línea al momento de marcar como visitado. Al parecer el commit que hice lo marcó como muchos cambios...

**Comment by jariasf** [comment]
Esa salida que mostraste es del código en Java o C++?

**Comment by jariasf** [comment]
Creo que el problema que tenias es con Java cierto? por que ahora que lo vi bien, el código esta bien. Solo que en Java esta por default como dirigido. Hay que cambiar una parte del código (set a false) para que sea no dirigido.

**Comment by Daviid-Perez-S** [comment]
Es del código en Java. Llegué hasta él mediante el link de tu blog.
La impresión es de la consola de NetBeans IDE 8.2

**Comment by Daviid-Perez-S** [comment]
Ah de ser que sí porque sigo teniendo el mismo error jajaja.
Deja lo voy a checar eso que dices, no lo había visto, gracias.

**Comment by Daviid-Perez-S** [comment]
Ok, ciertamente estabas en lo correcto, una disculpa, no había visto eso jeje. Cambiando el modo de inserción de las aristas a "false", ya todo funciona bien.
Sale gracias de nuevo.
